In [1]:
from pandasql import sqldf
import pandas as pd

In [2]:
airbnb = pd.read_csv("train_users_2.csv")
global airbnb

In [3]:
# overview of the data
pysqldf = lambda q: sqldf(q, globals())
q = """
SELECT * FROM airbnb
LIMIT 5
"""
pysqldf(q)

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,2010-06-28,20090319043255,None,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF
1,820tgsjxq7,2011-05-25,20090523174809,None,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,NDF
2,4ft3gnwmtx,2010-09-28,20090609231247,2010-08-02,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,US
3,bjjt8pjhuk,2011-12-05,20091031060129,2012-09-08,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,other
4,87mebub9p4,2010-09-14,20091208061105,2010-02-18,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,US

In [4]:
# check if there are duplicates in id
duplicate = '''
SELECT * FROM airbnb
GROUP BY id
HAVING COUNT(*) > 1
'''
pysqldf(duplicate)

Empty DataFrame
Columns: [id, date_account_created, timestamp_first_active, date_first_booking, gender, age, signup_method, signup_flow, language, affiliate_channel, affiliate_provider, first_affiliate_tracked, signup_app, first_device_type, first_browser, country_destination]
Index: []

In [6]:
# check if there is any missing value in data_first_booking
missing = '''
SELECT * FROM airbnb
WHERE date_first_booking IS NULL 
'''
pysqldf(missing)

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,2010-06-28,20090319043255,None,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF
1,820tgsjxq7,2011-05-25,20090523174809,None,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,NDF
2,om1ss59ys8,2010-01-05,20100105051812,None,FEMALE,47.0,basic,0,en,other,craigslist,untracked,Web,iPhone,-unknown-,NDF
3,dy3rgx56cu,2010-01-05,20100105083259,None,FEMALE,37.0,basic,0,en,other,craigslist,linked,Web,Mac Desktop,Firefox,NDF
4,ju3h98ch3w,2010-01-07,20100107055820,None,FEMALE,36.0,basic,0,en,other,craigslist,untracked,Web,iPhone,Mobile Safari,NDF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124538,zxodksqpep,2014-06-30,20140630235636,None,MALE,32.0,basic,0,en,sem-brand,google,omg,Web,Mac Desktop,Safari,NDF
124539,mhewnxesx9,2014-06-30,20140630235719,None,-unknown-,NaN,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
124540,6o3arsjbb4,2014-06-30,20140630235754,None,-unknown-,32.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,NDF
124541,jh95kwisub,2014-06-30,20140630235822,None,-unknown-,NaN,basic,25,en,other,other,tracked-other,iOS,iPhone,Mobile Safari,NDF
124542,nw9fwlyb5f,2014-06-30,20140630235824,None,-unknown-,NaN,basic,25,en,direct,direct,untracked,iOS,iPhone,-unknown-,NDF

In [10]:
# check if there is any missing value in data_first_booking
missing = '''
SELECT * FROM airbnb
WHERE age is NULL
'''
pysqldf(missing)

,id,date_account_created,timestamp_first_active,date_first_booking,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,country_destination
0,gxn3p5htnn,2010-06-28,20090319043255,None,-unknown-,None,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,NDF
1,osr2jwljor,2010-01-01,20100101215619,2010-01-02,-unknown-,None,basic,0,en,other,other,omg,Web,Mac Desktop,Chrome,US
2,k6np330cm1,2010-01-05,20100105060859,2010-01-18,-unknown-,None,basic,0,en,direct,direct,None,Web,Other/Unknown,-unknown-,FR
3,2dwbwkx056,2010-01-07,20100107215125,None,-unknown-,None,basic,0,en,other,craigslist,None,Web,Other/Unknown,-unknown-,NDF
4,cxlg85pg1r,2010-01-08,20100108015641,None,-unknown-,None,basic,0,en,seo,facebook,None,Web,Other/Unknown,-unknown-,NDF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87985,rf0ay567js,2014-06-30,20140630235309,None,-unknown-,None,basic,0,en,sem-brand,google,omg,Web,Mac Desktop,Chrome,NDF
87986,40o1ivh6cb,2014-06-30,20140630235352,None,-unknown-,None,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
87987,mhewnxesx9,2014-06-30,20140630235719,None,-unknown-,None,basic,0,en,direct,direct,linked,Web,Windows Desktop,Chrome,NDF
87988,jh95kwisub,2014-06-30,20140630235822,None,-unknown-,None,basic,25,en,other,other,tracked-other,iOS,iPhone,Mobile Safari,NDF
87989,nw9fwlyb5f,2014-06-30,20140630235824,None,-unknown-,None,basic,25,en,direct,direct,untracked,iOS,iPhone,-unknown-,NDF

In [11]:
# check if there is outlier in age
age_range = '''
SELECT MIN(age), MAX(age) FROM airbnb
'''
pysqldf(age_range)

   MIN(age)  MAX(age)
0       1.0    2014.0

In [16]:
# check if there is outlier in age
age_outlier = '''
SELECT age FROM airbnb
WHERE age > 80
ORDER BY age DESC
'''
pysqldf(age_outlier)

         age
0     2014.0
1     2014.0
2     2014.0
3     2014.0
4     2014.0
...      ...
2766    81.0
2767    81.0
2768    81.0
2769    81.0
2770    81.0

[2771 rows x 1 columns]